# Generated by Django 5.1.15 on 2026-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
