# Generated by Django 5.1.15 on 2026-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Enter one learning outcome per line.'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_content',
            field=models.TextField(blank=True, help_text='Course material visible only to enrolled learners.'),
        ),
    ]
